version: "3.8"

services:
   db:
      image: postgres:16
      container_name: cinema_db
      restart: always
      environment:
         POSTGRES_USER: cinema_user
         POSTGRES_PASSWORD: cinema_pass
         POSTGRES_DB: cinema_db
      ports:
         - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
